apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-depth1
  name: python-depth1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-depth1
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-depth2
  name: python-depth2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-depth2
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-depth3
  name: python-depth3
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-depth3
  type: ClusterIP
status:
  loadBalancer: {}

