apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-detection1
  name: python-detection1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-detection1
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-detection2
  name: python-detection2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-detection2
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-detection3
  name: python-detection3
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-detection3
  type: ClusterIP
status:
  loadBalancer: {}

