
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python-teian
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: python-teian
  type: NodePort
status:
  loadBalancer: {}